=== svn2github/marabou/xml/config/mrbcode.dtd
<!--	mrbcode.dtd
		Code Generator for MARaBOU
		Version 1.0
		19-Nov-2007
		R. Lutter
		Email: Rudi.Lutter@Physik.Uni-Muenchen.DE
-->

<!-- entities -->

<!-- as known form html -->
<!ENTITY amp "&#38;">
<!ENTITY gt "&#62;">
<!ENTITY lt "&#60;">

<!-- derived -->
<!ENTITY sout "&lt;&lt;">
<!ENTITY addr "&amp;">
<!ENTITY ptr "-&gt;">
<!ENTITY and "&amp;&amp;">

<!ELEMENT mrbcode (file | (code | class | method | funct | ctor | include)*)>

<!-- text with substitutions -->
<!ENTITY % stext "(#PCDATA | s | S |  m | mm | r | rm)*">
<!-- text to be used in comments: substitutions, bold/italic/underlined, boxed, and line break -->
<!ENTITY % ctext "(#PCDATA | s | S |  m | mm  | r | rm | b | i | u | bx | nl)*">

<!-- file spec -->
<!ELEMENT file (tag, slist?, fileHdr, (code | foreach)*, (class | method | funct | include)+)>

<!-- file header -->
<!ELEMENT fileHdr (xname, gname, purp?, descr?, rootClassList?, mrbClassList?, author, mail, url, version, date?)>

<!-- C++ class definition -->
<!ELEMENT class (tag?, classHdr, code)>
<!-- C++ class header -->
<!ELEMENT classHdr (cname, purp, inheritance?, argList?, descr?)>
<!-- C++ class constructor -->
<!ELEMENT ctor (tag?, ctorHdr, code)>
<!-- C++ constructor header -->
<!ELEMENT ctorHdr (cname, purp, argList?, descr?)>

<!-- C++ class method definition -->
<!ELEMENT method (tag?, methodHdr, (code | include)+)>
<!-- C++ class method header -->
<!ELEMENT methodHdr (mname, cname, purp, argList?, returnVal, descr?)>

<!-- function definition -->
<!ELEMENT funct (tag?, functHdr, (code | include)+)>
<!-- function header -->
<!ELEMENT functHdr (fname, ftype, purp, argList?, returnVal, descr?)>

<!-- include code from other file -->
<!ELEMENT include (tag?, fpath?, descr?)>

<!-- piece of code -->
<!ELEMENT code (tag?, comment?, slist?, (switch | foreach | if | code | cbody | include | nl)*)>
<!-- code body -->
<!ELEMENT cbody (switch | if | l | nl)*>

 <!-- if clause -->
<!ELEMENT if (flag, flagValue?, descr?, (cbody | include)+)>

<!-- code loop -->
<!ELEMENT foreach (tag?, comment?, item, descr?, slist?, (cbody | switch | if | include)+)>

<!-- code selection depending on tag -->
<!ELEMENT switch (item, case+)>
<!-- case: tagged piece of code -->
<!ELEMENT case (tag, descr?, (cbody | include)+)>

<!-- item -->
<!ELEMENT item (#PCDATA)>

<!-- function type -->
<!ELEMENT ftype (#PCDATA)>

<!-- argument list -->
<!ELEMENT argList (arg)+>
<!-- single argument -->
<!ELEMENT arg (aname, atype, descr?)>
<!-- argument type -->
<!ELEMENT atype %stext;>
<!-- return value (class method or function) -->
<!ELEMENT returnVal (arg)>

<!-- comment -->
<!ELEMENT comment %ctext;>

<!-- list of links referencing ROOT objects -->
<!ELEMENT rootClassList (classRef+)>
<!-- list of links referencing MARaBOU objects -->
<!ELEMENT mrbClassList (classRef+)>
<!-- inheritance list to be included in class header -->
<!ELEMENT inheritance (classRef+)>
<!-- class reference -->
<!ELEMENT classRef (cname, descr?)>

<!-- tags to mark pieces of code -->
<!ELEMENT tag (#PCDATA)>
<!-- flag to be used in if clause -->
<!ELEMENT flag (#PCDATA)>
<!-- flag value to be used in if clause -->
<!ELEMENT flagValue (#PCDATA)>

<!-- list of substitutions -->
<!ELEMENT slist (subst)+>
<!-- substitution: to be replaced by value on code generation -->
<!ELEMENT subst (sname, descr?)>

<!-- file path -->
<!ELEMENT fpath %stext;>
<!-- name of xml file -->
<!ELEMENT xname %stext;>
<!-- name of generated code file -->
<!ELEMENT gname %stext;>
<!-- class name -->
<!ELEMENT cname %stext;>
<!-- method name -->
<!ELEMENT mname %stext;>
<!-- function name -->
<!ELEMENT fname %stext;>
<!-- name of a variable-->
<!ELEMENT vname %stext;>
<!-- name of argument -->
<!ELEMENT aname %stext;>
<!-- name of substitution -->
<!ELEMENT sname %stext;>
<!-- purpose -->
<!ELEMENT purp %stext;>
<!-- description (file, class, method, etc ...) -->
<!ELEMENT descr %ctext;>
<!-- author's name -->
<!ELEMENT author %stext;>
<!-- author's mail -->
<!ELEMENT mail %stext;>
<!-- author's url -->
<!ELEMENT url %stext;>

<!-- version (cvs: $Id: mrbcode.dtd,v 1.4 2008-02-18 12:29:03 Rudolf.Lutter Exp $) -->
<!ELEMENT version (#PCDATA)>
<!-- date (cvs: $Date: 2008-02-18 12:29:03 $) -->
<!ELEMENT date (#PCDATA)>

<!-- to be substituted -->
<!ELEMENT s (#PCDATA)>
<!-- to be substituted (1st char upper case) -->
<!ELEMENT S (#PCDATA)>

<!-- line of code -->
<!ELEMENT l %stext;>

<!-- bold, italic, underline, box -->
<!ELEMENT b (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT u (#PCDATA)>
<!ELEMENT bx (#PCDATA)>

<!-- newline -->
<!ELEMENT nl EMPTY>

<!-- root and marabou links -->
<!ELEMENT r (#PCDATA)>
<!ELEMENT m (#PCDATA)>
<!ELEMENT rm (#PCDATA)>
<!ELEMENT mm (#PCDATA)>

<!-- attribut lists -->

<!-- mrbcode -->
<!ATTLIST  mrbcode
   type    (contiguous|selective) "contiguous"
>

<!-- indentation -->
<!ATTLIST  class
    indent    CDATA    "0"
>
<!ATTLIST  method
    indent    CDATA    "0"
>
<!ATTLIST  funct
    indent    CDATA    "0"
>
<!ATTLIST  code
    indent    CDATA    "0"
>

<!ATTLIST  switch
    indent    CDATA    "0"
>
<!ATTLIST  foreach
    indent    CDATA    "0"
>
<!ATTLIST  if
    indent    CDATA    "0"
>
<!ATTLIST  cbody
    indent    CDATA    "0"
>

<!ATTLIST  include
    indent    CDATA    "0"
>

<!-- comment -->
<!ATTLIST comment
    type    (code|doc) "code"
 >
 
<!-- slist -->
<!ATTLIST slist
    type    (global|local) "global"
 >
 
<!-- tag -->
<!ATTLIST tag
    type    (root|local) "local"
 >
 
 <!-- inheritance type -->
<!ATTLIST inheritance
    type    (root|mrb) #REQUIRED
 >
 
<!-- r (root) and m (marabou) class refs -->
<!ATTLIST r
    class CDATA #IMPLIED
 >
<!ATTLIST m
    class CDATA #IMPLIED
 >
<!-- r (root) and m (marabou) method refs -->
<!ATTLIST rm
    class CDATA #REQUIRED
 >
<!ATTLIST mm
    class CDATA #REQUIRED
 >

=== svn2github/marabou/templates/config-xml/Analyze_OtherMethods.cxx.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE mrbcode SYSTEM "mrbcode.dtd">

<?xml-stylesheet type="text/xsl" href="mrbcode.xsl" ?>

<mrbcode type="selective"><method indent="1">
    <tag>WDW_ADJUST_POINTERS</tag>
    <methodHdr>
        <mname>AdjustWindowPointers</mname>
        <cname><m>TMrbAnalyze</m></cname>
        <purp>Adjust pointers to (2-dim) windows after reload</purp>
        <returnVal>
            <arg>
                <aname>Flag</aname>
                <atype>Bool_t</atype>
                <descr>kTRUE/kFALSE</descr>
            </arg>
        </returnVal>
        <descr>2-dim window objects have changed their addresses after reload.<nl/>Pointers therefore have to be adjusted to new addresses.</descr>
    </methodHdr>
    <foreach indent="2">
        <item>window</item>
        <slist>
            <subst><sname>wdwName</sname><descr>window name</descr></subst>
            <subst><sname>wdwClass</sname><descr>class name</descr></subst>
        </slist>
        <cbody>
            <l><s>wdwName</s> = (<s>wdwClass</s> *) <m class="TMrbLofUserVars">gMrbLofUserVars</m>-><mm class="TMrbLofUserVars">Find</mm>("<s>wdwName</s>");</l>
        </cbody>
    </foreach>			
    <code indent="2">
        <cbody>
            <l>return(kTRUE);</l>
        </cbody>
    </code>			
</method>
    <method indent="1">
        <tag>EVT_SET_SCALEDOWN</tag>
        <methodHdr>
            <mname>SetScaleDown</mname>
            <cname><m>TMrbAnalyze</m></cname>
            <purp>Set a scale-down value common to all events</purp>
            <argList>
                <arg>
                    <aname>ScaleDown</aname>
                    <atype>Int_t</atype>
                    <descr>scale-down factor</descr>
                </arg>
            </argList>
            <descr>Defines a global scale-down factor valid for all events.</descr>
        </methodHdr>
        <code>			
            <cbody><l>fScaleDown = ScaleDown;</l></cbody>
        </code>
        <foreach indent="2">
            <comment type="code">set scale down individually for each event</comment>
            <item>event</item>
            <descr>once per event</descr>
            <slist>
                <subst><sname>className</sname><descr>class name</descr></subst>
                <subst><sname>evtName</sname><descr>event name</descr></subst>
                <subst><sname>trigNo</sname><descr>trigger number</descr></subst>
                <subst><sname>eventType</sname><descr>event type: E=readout/hardware, U=user-defined</descr></subst>
            </slist>
            <switch indent="3">
                <item>eventType</item>
                <case>
                    <tag>E</tag>
                    <descr>normal (hardware) event</descr>
                    <cbody>
                        <l>// event <s>evtName</s>, trigger <s>trigNo</s></l>
                        <l>g<S>evtName</S>->SetScaleDown(ScaleDown);</l>
                    </cbody>
                </case>
                <case>
                    <tag>U</tag>
                    <descr>user-defined event</descr>
                    <cbody>
                        <l>// user-defined event <s>className</s></l>
                        <l>g<S>className</S>->SetScaleDown(ScaleDown);</l>
                    </cbody>
                </case>
            </switch>
        </foreach>
    </method>
</mrbcode>

=== svn2github/marabou/templates/config-xml/Subevent_Caen_Common.cxx.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE mrbcode SYSTEM "mrbcode.dtd">

<?xml-stylesheet type="text/xsl" href="mrbcode.xsl" ?>

<mrbcode type="selective">
	<method>
		<tag>SEVT_CLASS_METHODS</tag>
		<methodHdr>
			<mname>FillSubevent</mname>
			<cname>TMrbSubevent_Caen</cname>
			<purp>Decode CAEN buffer</purp>
			<argList>
				<arg>
					<aname>SevtData</aname>
					<atype>const UShort_t *</atype>
					<descr>pointer to unpacked subevent data</descr>
				</arg>
				<arg>
					<aname>SevtWC</aname>
					<atype>Int_t</atype>
					<descr>word count</descr>
				</arg>
				<arg>
					<aname>TimeStamp</aname>
					<atype>Int_t</atype>
					<descr>time since last start</descr>
				</arg>
			</argList>
			<returnVal>
				<arg>
					<aname>Flag</aname>
					<atype>Bool_t</atype>
					<descr>kTRUE/kFALSE</descr>
				</arg>
			</returnVal>
			<descr>Decodes data from a CAEN Vxxx</descr>
		</methodHdr>
		<code>
			<cbody>
				<l>fTimeStamp = TimeStamp; 				// store time since last "start acquisition"</l>
				<l>this->SetTimeStamp(TimeStamp);				// passed as argument by parent event</l>
				<l>this->GetHitBuffer()->Reset();				// clear hit buffer</l>
				<nl/>
				<l>recNo++;							// count this record</l>	
				<l>Int_t origSevtWC = SevtWC;				// save original subevent wc</l>
				<l>if (forcedDump &amp;&amp; (SevtWC > 0)) <m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">DumpData</mm>("sevt", recNo, this->ClassName(), "FillSubevent", "Forced dump", SevtData, origSevtWC);</l>
				<l>Int_t wordsProcessed = 0; 				// words processed so far</l>
				<l>UShort_t * dataPtr = (UShort_t *) SevtData;</l>
				<l>Int_t eventsProcessed = 0;</l>
				<l>while (SevtWC > 0) {					// subevent may contain several CAEN modules</l>
				<l>	Int_t header = (*dataPtr++) &lt;&lt; 16; 			// header word (MSB)</l>
				<l>	header |= *dataPtr++; 				// header word (LSB)</l>
				<l>	if ((header &amp; CAEN_Vxxx_D_HDR) == 0) {</l>
				<l>		<m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">DumpData</mm>("sevt", recNo, this->ClassName(), "FillSubevent", "Wrong header", SevtData, origSevtWC);</l>
				<l>		cerr	&lt;&lt; setred</l>
				<l>			&lt;&lt; this->ClassName() &lt;&lt; "::FillSubevent() [sevtWC="</l>
				<l>			&lt;&lt; wordsProcessed &lt;&lt; "] Wrong header - 0x" &lt;&lt; setbase(16) &lt;&lt; header &lt;&lt; setbase(10)</l>
				<l>			&lt;&lt; setblack &lt;&lt; endl;</l>
				<l>		return(kTRUE);</l>
				<l>	}</l>
				<l>	Int_t wc = (header >> CAEN_Vxxx_SH_WC) &amp; CAEN_Vxxx_M_WC;				// extract wc</l>
				<l>	Int_t wcs = wc;</l>
				<l>	if (wc &lt; 0 || wc &gt; 32) {				// max 32 data words</l>
				<l>		<m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">DumpData</mm>("sevt", recNo, this->ClassName(), "FillSubevent", "Wrong word count", SevtData, origSevtWC);</l>
				<l>		cerr	&lt;&lt; setred</l>
				<l>			&lt;&lt; this->ClassName() &lt;&lt; "::FillSubevent() [sevtWC="</l>
				<l>			&lt;&lt; wordsProcessed &lt;&lt; "] Wrong word count - " &lt;&lt; wc &lt;&lt; setblack &lt;&lt; endl;</l>
				<l>		return(kTRUE);</l>
				<l>	}</l>
				<l>	Int_t moduleNumber = header &amp; CAEN_Vxxx_M_MSERIAL;	// extract module number</l>
				<l>	TMrbModuleListEntry * mle = <m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">GetModuleListEntry</mm>(moduleNumber);</l>
				<l>	if (mle == NULL) {</l>
				<l>		<m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">DumpData</mm>("sevt", recNo, this->ClassName(), "FillSubevent", "Wrong module number", SevtData, origSevtWC);</l>
				<l>		cerr	&lt;&lt; setred</l>
				<l>			&lt;&lt; this->ClassName() &lt;&lt; "::FillSubevent() [sevtWC="</l>
				<l>			&lt;&lt; wordsProcessed &lt;&lt; "] Wrong module number - " &lt;&lt; moduleNumber</l>
				<l>			&lt;&lt; setblack &lt;&lt; endl;</l>
				<l>		return(kTRUE);</l>
				<l>	}</l>
				<nl/>
				<l>	if (eventsProcessed >= CAEN_Vxxx_N_MAXEVENTS) {</l>
				<l>		<m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">DumpData</mm>("sevt", recNo, this->ClassName(), "FillSubevent", "Too many events", SevtData, origSevtWC);</l>
				<l>		cerr	&lt;&lt; setred</l>
				<l>			&lt;&lt; this->ClassName() &lt;&lt; "::FillSubevent(): [Module "</l>
				<l>			&lt;&lt; <m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">GetModuleName</mm>(moduleNumber) &lt;&lt; " (" &lt;&lt; moduleNumber &lt;&lt; "), sevtWC="</l>
				<l>			&lt;&lt; wordsProcessed &lt;&lt; "] Too many events - max " &lt;&lt; CAEN_Vxxx_N_MAXEVENTS &lt;&lt; setblack &lt;&lt; endl;</l>
				<l>		return(kTRUE);</l>
				<l>	}</l>
				<nl/>
				<l>	mle->IncrEventHits();				// count this event</l>
				<nl/>
				<l>	UShort_t evtData[2];</l>
				<l>	for (; wc; wc--) {</l>
				<l>		Int_t data = (*dataPtr++) &lt;&lt; 16;		// data (MSB)</l>
				<l>		data |= *dataPtr++; 			// data (LSB)</l>
				<l>		if ((data &amp; CAEN_Vxxx_M_ID) != CAEN_Vxxx_D_DATA) {</l>
				<l>			if ((data &amp; CAEN_Vxxx_M_ID) == CAEN_Vxxx_D_EOB) {</l>
				<l>				<m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">DumpData</mm>("sevt", recNo, this->ClassName(), "FillSubevent", "Unexpected EOB", SevtData, origSevtWC);</l>
				<l>				cerr	&lt;&lt; setred</l>
				<l>					&lt;&lt; this->ClassName() &lt;&lt; "::FillSubevent(): [Module "</l>
				<l>					&lt;&lt; <m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">GetModuleName</mm>(moduleNumber) &lt;&lt; " (" &lt;&lt; moduleNumber &lt;&lt; "), sevtWC=" &lt;&lt; wordsProcessed</l>
				<l>					&lt;&lt; "] Unexpected EOB - remaining wc=" &lt;&lt; wc &lt;&lt; " ignored. Continuing with next event."</l>
				<l>					&lt;&lt; setblack &lt;&lt; endl;</l>
				<l>				dataPtr -= 2;</l>
				<l>				wcs -= wc;</l>
				<l>				break;</l>
				<l>			} else {</l>
				<l>				<m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">DumpData</mm>("sevt", recNo, this->ClassName(), "FillSubevent", "Wrong data", SevtData, origSevtWC);</l>
				<l>				cerr	&lt;&lt; setred</l>
				<l>					&lt;&lt; this->ClassName() &lt;&lt; "::FillSubevent(): [Module "</l>
				<l>					&lt;&lt; <m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">GetModuleName</mm>(moduleNumber) &lt;&lt; " (" &lt;&lt; moduleNumber &lt;&lt; "), sevtWC="</l>
				<l>					&lt;&lt; wordsProcessed &lt;&lt; "] Wrong data - 0x" &lt;&lt; setbase(16) &lt;&lt; data &lt;&lt; setbase(10)</l>
				<l>					&lt;&lt; setblack &lt;&lt; endl;</l>
				<l>				return(kTRUE);</l>
				<l>			}</l>
				<l>		}</l>
				<l>		Int_t chn = (data >> CAEN_Vxxx_SH_CHN) &amp; CAEN_Vxxx_M_CHN;</l>
				<l>		mle->IncrChannelHits(chn);			// count this channel</l>
				<l>		evtData[0] = 0;</l>
				<l>		if (data &amp; CAEN_Vxxx_B_OVERFLOW) evtData[1] = CAEN_Vxxx_B_OVERFLOW;</l>
				<l>		else if (data &amp; CAEN_Vxxx_B_UNDERTHRESH) evtData[1] = (UShort_t) -1;</l>
				<l>		else evtData[1] = (UShort_t) (data &amp; CAEN_Vxxx_M_ADCDATA);</l>
				<l>		this->GetHitBuffer()->AddHit(	eventsProcessed,</l>
				<l>							moduleNumber,</l>
				<l>							chn,</l>
				<l>							NULL,</l>
				<l>							evtData, 2);</l>
				<l>	}</l>
				<l>	Int_t trailer = (*dataPtr++) &lt;&lt; 16; 					// trailer word (MSB)</l>
				<l>	trailer |= *dataPtr++; 									// trailer word (LSB)</l>
				<l>	if ((trailer &amp; CAEN_Vxxx_D_EOB) == 0) {</l>
				<l>		<m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">DumpData</mm>("sevt", recNo, this->ClassName(), "FillSubevent", "Wrong EOB", SevtData, origSevtWC);</l>
				<l>		cerr	&lt;&lt; setred</l>
				<l>			&lt;&lt; this->ClassName() &lt;&lt; "::FillSubevent(): [Module "</l>
				<l>			&lt;&lt; <m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">GetModuleName</mm>(moduleNumber) &lt;&lt; " (" &lt;&lt; moduleNumber &lt;&lt; "), sevtWC="</l>
				<l>			&lt;&lt; wordsProcessed &lt;&lt; "] Wrong EOB - 0x" &lt;&lt; setbase(16) &lt;&lt; trailer &lt;&lt; setbase(10)</l>
				<l>			&lt;&lt; setblack &lt;&lt; endl;</l>
				<l>		return(kTRUE);</l>
				<l>	}</l>
				<l>	wcs = (wcs + 2) * 2;</l>
				<l>	SevtWC -= wcs;						// remaining subevent data</l>
				<l>	wordsProcessed += wcs;</l>
				<l>	eventsProcessed++;</l>
				<l>}</l>
				<l>return(kTRUE);</l>
			</cbody>
		</code>
	</method>
	<code>
		<tag>INCLUDE_EVT_SEVT_MOD_GLOBALS</tag>
		<cbody><l>// This was called by <s>sevtName</s></l></cbody>
	</code>
</mrbcode>

=== svn2github/marabou/templates/config-xml/Analyze.cxx.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE mrbcode SYSTEM "mrbcode.dtd">

<?xml-stylesheet type="text/xsl" href="mrbcode.xsl" ?>

<mrbcode type="contiguous">
	<file>
		<tag type="root">ANA_XML_ROOT</tag>
		<slist type="global">
			<subst><sname>xprefix</sname><descr>description/name of experiment</descr></subst>
			<subst><sname>expTitle</sname><descr>title of experiment</descr></subst>
			<subst><sname>author</sname><descr>author's name</descr></subst>
			<subst><sname>mailAddr</sname><descr>author's mail address</descr></subst>
			<subst><sname>URL</sname><descr>author's URL</descr></subst>
			<subst><sname>purpose</sname><descr>purpose of this code</descr></subst>
		</slist>
		<fileHdr>
			<xname>Analyze.cxx.xml</xname>
			<gname><S>xprefix</S>Analyze.cxx</gname>
			<purp><S>purpose</S></purp>
			<rootClassList>	<classRef><cname>TSystem</cname><descr>Interface ROOT&lt;-&gt;Linux</descr></classRef>
						<classRef><cname>TEnv</cname><descr>ROOT's environment</descr></classRef>
			</rootClassList>
			<mrbClassList>	<classRef><cname>TMrbLogger</cname><descr>Message logger</descr></classRef>
						<classRef><cname>TMrbTransport</cname><descr>Transport manager MBS-&gt;ROOT</descr></classRef>
						<classRef><cname>TMrbAnalyze</cname><descr>Base object for user's acquisition/analysis</descr></classRef>
						<classRef><cname>TMrbLofUserVars</cname><descr>List of user variables</descr></classRef>
						<classRef><cname>TMrbIOSpec</cname><descr>I/O specifications</descr></classRef>
						<classRef><cname>TUsrEvtStart</cname><descr>Start event</descr></classRef>
						<classRef><cname>TUsrEvtStop</cname><descr>Stop event</descr></classRef>
						<classRef><cname>TUsrDeadTime</cname><descr>Dead time monitor</descr></classRef>
			</mrbClassList>
			<author><S>author</S></author>
			<mail><s>mailAddr</s></mail>
			<url><s>URL</s></url>
			<version>$Id: Analyze.cxx.xml,v 1.1 2008/03/05 12:43:17 Rudolf.Lutter Exp $</version>
			<date>$Date: 2008/03/05 12:43:17 $</date>
		</fileHdr>
		<code indent="1">
			<comment type="code">class definitions</comment>
			<cbody>
				<l>#include "<S>xprefix</S>Analyze.h"</l>
			</cbody>
		</code>
		<code indent="1">
			<comment type="code">common index declarations for analysis and readout</comment>
			<cbody>
				<l>#include "<S>xprefix</S>CommonIndices.h"</l>
			</cbody>
		</code>
		<code indent="1">
			<cbody>
				<l>#include "SetColor.h"</l><l>#include "pthread.h" 	// pthread header file</l>
			</cbody>
		</code>
		<foreach indent="1">
			<tag>INCLUDE_USER_GLOBALS</tag>
			<comment type="code">global defs supplied by user</comment>
			<item>file</item>
			<descr>more than one file possible</descr>
			<slist><subst><sname>iclFile</sname><descr>file containing globals defined by user</descr></subst></slist>
			<cbody>
				<l>#include "<s>iclFile</s>"</l>
			</cbody>
		</foreach>
		<code indent="1">
			<comment type="code">global objects</comment>
			<cbody>
				<l>#include "<S>xprefix</S>AnalyzeGlobals.h"</l>
			</cbody>
		</code>
		<code indent="1">
			<tag>INCLUDE_EVT_SEVT_MOD_GLOBALS</tag>
			<comment type="code">special global defs for events, subevents, and modules</comment>
			<foreach indent="2">
				<item>event</item>
				<descr>once per event</descr>
				<slist>
					<subst><sname>evtName</sname><descr>event name</descr></subst>
					<subst><sname>codeFile</sname><descr>file containing global defs</descr></subst>
				</slist>
				<include indent="3"><fpath type="subst"><s>codeFile</s></fpath><descr>event-specific definitions</descr></include>
			</foreach>
			<foreach indent="2">
				<item>subevent</item>
				<descr>once per subevent</descr>
				<slist>
					<subst><sname>sevtName</sname><descr>subevent name</descr></subst>
					<subst><sname>codeFile</sname><descr>file containing global defs</descr></subst>
				</slist>
				<include indent="3"><fpath type="subst"><s>codeFile</s></fpath><descr>subevent-specific definitions</descr></include>
			</foreach>
			<foreach indent="2">
				<item>module</item>
				<descr>once per module</descr>
				<slist>
					<subst><sname>moduleName</sname><descr>module name</descr></subst>
					<subst><sname>codeFile</sname><descr>file containing global defs</descr></subst>
				</slist>
				<include indent="3"><fpath type="subst"><s>codeFile</s></fpath><descr>module-specific definitions</descr></include>
			</foreach>
		</code>
		<foreach indent="1">
			<tag>IMPLEMENT_CLASSES</tag>
			<comment type="code">implement class defs</comment>
			<item>class</item>
			<descr>one statement per class</descr>
			<slist><subst><sname>cname</sname><descr>class name</descr></subst></slist>
			<cbody>
				<l>ClassImp(<s>cname</s>)</l>
			</cbody>
		</foreach>
		<code indent="1">
			<comment type="code">global vars and external refs</comment>
			<cbody>
				<l>extern pthread_mutex_t global_data_mutex;			//  global pthread mutex to protect TMapped data</l>
				<nl/>
				<l>extern <m>TMrbLogger</m> * gMrbLog;					//  MARaBOU's logging mechanism</l>
				<nl/>
				<l>extern <m>TMrbTransport</m> * gMrbTransport;				//  base class for MBS transport</l>
				<l>extern <m>TMrbAnalyze</m> * gMrbAnalyze;				//  base class for user's analysis</l>
				<nl/>				
				<l>extern <m>TUsrEvtStart</m> * gStartEvent;					//  start + stop events</l>
				<l>extern <m>TUsrEvtStop</m> * gStopEvent;</l>
				<l>extern <m>TUsrDeadTime</m> * gDeadTime;				//  dead-time data</l>
				<nl/>				
				<l>extern <m>TMrbLofUserVars</m> * gMrbLofUserVars;			//  list of user vars/wdws</l>
				<nl/>				
				<l>static Bool_t verboseMode = kFALSE;					//  verbosity flag;</l>
				<l>static Bool_t forcedDump = kFALSE;				//  kTRUE -> dump records</l>
				<l>static Int_t recNo = 0;</l>
			</cbody>
		</code>
		
		<include indent="1">
			<fpath>Analyze_Initialize.cxx.xml</fpath>
			<clist><content><cname><m>TMrbAnalyze</m>::Initialize()</cname><descr>[C++ method]</descr></content></clist>
			<descr>Instantiate user objects, initialize values</descr>
		</include>
		<include indent="1">
			<tag>DUMMY_INITIALIZE_CODE</tag>
			<fpath>Analyze_DummyMethods.cxx.xml</fpath>
			<clist><content><cname><m>TMrbAnalyze</m>::InitializeUserCode()</cname><descr>[C++ method] Initialize user code</descr></content></clist>
			<descr>Dummy methods, may be overwritten by user code</descr>
		</include>
		<include indent="1">
			<tag>DUMMY_HANDLE_MESSAGES</tag>
			<fpath>Analyze_DummyMethods.cxx.xml</fpath>
			<clist><content><cname><m>TMrbAnalyze</m>::HandleMessage()</cname><descr>[C++ method] Respond to message requests sent by the message handler</descr></content></clist>
			<descr>Dummy methods, may be overwritten by user code</descr>
		</include>
		<include indent="1">
			<tag>DUMMY_RELOAD_PARAMS</tag>
			<fpath>Analyze_DummyMethods.cxx.xml</fpath>
			<clist><content><cname><m>TMrbAnalyze</m>::ReloadParams()</cname><descr>[C++ method] Reload parameters from file</descr></content></clist>
			<descr>Dummy methods, may be overwritten by user code</descr>
		</include>
		<include indent="1">
			<tag>DUMMY_FINISH_RUN</tag>
			<fpath>Analyze_DummyMethods.cxx.xml</fpath>
			<clist><content><cname><m>TMrbAnalyze</m>::FinishRun()</cname><descr>[C++ method] Do some work at end of run</descr></content></clist>
			<descr>Dummy methods, may be overwritten by user code</descr>
		</include>
		<include indent="1">
			<fpath>Analyze_WriteRootTree.cxx.xml</fpath>
			<clist><content><cname><m>TMrbAnalyze</m>::WriteRootTree()</cname><descr>[C++ method]</descr></content></clist>
			<descr>Open a file to write raw data to tree</descr>
		</include>
		<include indent="1">
			<fpath>Analyze_OpenRootFile.cxx.xml</fpath>
			<clist><content><cname><m>TMrbAnalyze</m>::OpenRootFile()</cname><descr>[C++ method]</descr></content></clist>
			<descr>Open a file to replay tree data</descr>
		</include>
		<include indent="1">
			<fpath>Analyze_ReplayTreeData.cxx.xml</fpath>
			<clist><content><cname><m>TMrbAnalyze</m>::ReplayTreeData()</cname><descr>[C++ method]</descr></content></clist>
			<descr>Read data from ROOT file (replay only)</descr>
		</include>
		<include indent="1">
			<tag>EVT_SET_SCALEDOWN</tag>
			<fpath>Analyze_OtherMethods.cxx.xml</fpath>
			<clist><content><cname><m>TMrbAnalyze</m>::SetScaleDown()</cname><descr>[C++ method]</descr></content></clist>
			<descr>Set a scale-down value common to all events</descr>
		</include>
		<include indent="1">
			<tag>WDW_ADJUST_POINTERS</tag>
			<fpath>Analyze_OtherMethods.cxx.xml</fpath>
			<clist><content><cname><m>TMrbAnalyze</m>::AdjustWindowPointers()</cname><descr>[C++ method]</descr></content></clist>
			<descr>Adjust pointers to (2-dim) windows after reload</descr>
		</include>
	</file>
</mrbcode>
