=== svn2github/marabou/xml/config/mrbcode.dtd
<!--	mrbcode.dtd
		Code Generator for MARaBOU
		Version 1.0
		19-Nov-2007
		R. Lutter
		Email: Rudi.Lutter@Physik.Uni-Muenchen.DE
-->

<!-- entities -->

<!-- as known form html -->
<!ENTITY amp "&#38;">
<!ENTITY gt "&#62;">
<!ENTITY lt "&#60;">

<!-- derived -->
<!ENTITY sout "&lt;&lt;">
<!ENTITY addr "&amp;">
<!ENTITY ptr "-&gt;">
<!ENTITY and "&amp;&amp;">

<!ELEMENT mrbcode (file | (code | class | method | funct | ctor | include)*)>

<!-- text with substitutions -->
<!ENTITY % stext "(#PCDATA | s | S |  m | mm | r | rm)*">
<!-- text to be used in comments: substitutions, bold/italic/underlined, boxed, and line break -->
<!ENTITY % ctext "(#PCDATA | s | S |  m | mm  | r | rm | b | i | u | bx | nl)*">

<!-- file spec -->
<!ELEMENT file (tag, slist?, fileHdr, (code | foreach)*, (class | method | funct | include)+)>

<!-- file header -->
<!ELEMENT fileHdr (xname, gname, purp?, descr?, rootClassList?, mrbClassList?, author, mail, url, version, date?)>

<!-- C++ class definition -->
<!ELEMENT class (tag?, classHdr, code)>
<!-- C++ class header -->
<!ELEMENT classHdr (cname, purp, inheritance?, argList?, descr?)>
<!-- C++ class constructor -->
<!ELEMENT ctor (tag?, ctorHdr, code)>
<!-- C++ constructor header -->
<!ELEMENT ctorHdr (cname, purp, argList?, descr?)>

<!-- C++ class method definition -->
<!ELEMENT method (tag?, methodHdr, (code | include)+)>
<!-- C++ class method header -->
<!ELEMENT methodHdr (mname, cname, purp, argList?, returnVal, descr?)>

<!-- function definition -->
<!ELEMENT funct (tag?, functHdr, (code | include)+)>
<!-- function header -->
<!ELEMENT functHdr (fname, ftype, purp, argList?, returnVal, descr?)>

<!-- include code from other file -->
<!ELEMENT include (tag?, fpath?, descr?)>

<!-- piece of code -->
<!ELEMENT code (tag?, comment?, slist?, (switch | foreach | if | code | cbody | include | nl)*)>
<!-- code body -->
<!ELEMENT cbody (switch | if | l | nl)*>

 <!-- if clause -->
<!ELEMENT if (flag, flagValue?, descr?, (cbody | include)+)>

<!-- code loop -->
<!ELEMENT foreach (tag?, comment?, item, descr?, slist?, (cbody | switch | if | include)+)>

<!-- code selection depending on tag -->
<!ELEMENT switch (item, case+)>
<!-- case: tagged piece of code -->
<!ELEMENT case (tag, descr?, (cbody | include)+)>

<!-- item -->
<!ELEMENT item (#PCDATA)>

<!-- function type -->
<!ELEMENT ftype (#PCDATA)>

<!-- argument list -->
<!ELEMENT argList (arg)+>
<!-- single argument -->
<!ELEMENT arg (aname, atype, descr?)>
<!-- argument type -->
<!ELEMENT atype %stext;>
<!-- return value (class method or function) -->
<!ELEMENT returnVal (arg)>

<!-- comment -->
<!ELEMENT comment %ctext;>

<!-- list of links referencing ROOT objects -->
<!ELEMENT rootClassList (classRef+)>
<!-- list of links referencing MARaBOU objects -->
<!ELEMENT mrbClassList (classRef+)>
<!-- inheritance list to be included in class header -->
<!ELEMENT inheritance (classRef+)>
<!-- class reference -->
<!ELEMENT classRef (cname, descr?)>

<!-- tags to mark pieces of code -->
<!ELEMENT tag (#PCDATA)>
<!-- flag to be used in if clause -->
<!ELEMENT flag (#PCDATA)>
<!-- flag value to be used in if clause -->
<!ELEMENT flagValue (#PCDATA)>

<!-- list of substitutions -->
<!ELEMENT slist (subst)+>
<!-- substitution: to be replaced by value on code generation -->
<!ELEMENT subst (sname, descr?)>

<!-- file path -->
<!ELEMENT fpath %stext;>
<!-- name of xml file -->
<!ELEMENT xname %stext;>
<!-- name of generated code file -->
<!ELEMENT gname %stext;>
<!-- class name -->
<!ELEMENT cname %stext;>
<!-- method name -->
<!ELEMENT mname %stext;>
<!-- function name -->
<!ELEMENT fname %stext;>
<!-- name of a variable-->
<!ELEMENT vname %stext;>
<!-- name of argument -->
<!ELEMENT aname %stext;>
<!-- name of substitution -->
<!ELEMENT sname %stext;>
<!-- purpose -->
<!ELEMENT purp %stext;>
<!-- description (file, class, method, etc ...) -->
<!ELEMENT descr %ctext;>
<!-- author's name -->
<!ELEMENT author %stext;>
<!-- author's mail -->
<!ELEMENT mail %stext;>
<!-- author's url -->
<!ELEMENT url %stext;>

<!-- version (cvs: $Id: mrbcode.dtd,v 1.4 2008-02-18 12:29:03 Rudolf.Lutter Exp $) -->
<!ELEMENT version (#PCDATA)>
<!-- date (cvs: $Date: 2008-02-18 12:29:03 $) -->
<!ELEMENT date (#PCDATA)>

<!-- to be substituted -->
<!ELEMENT s (#PCDATA)>
<!-- to be substituted (1st char upper case) -->
<!ELEMENT S (#PCDATA)>

<!-- line of code -->
<!ELEMENT l %stext;>

<!-- bold, italic, underline, box -->
<!ELEMENT b (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT u (#PCDATA)>
<!ELEMENT bx (#PCDATA)>

<!-- newline -->
<!ELEMENT nl EMPTY>

<!-- root and marabou links -->
<!ELEMENT r (#PCDATA)>
<!ELEMENT m (#PCDATA)>
<!ELEMENT rm (#PCDATA)>
<!ELEMENT mm (#PCDATA)>

<!-- attribut lists -->

<!-- mrbcode -->
<!ATTLIST  mrbcode
   type    (contiguous|selective) "contiguous"
>

<!-- indentation -->
<!ATTLIST  class
    indent    CDATA    "0"
>
<!ATTLIST  method
    indent    CDATA    "0"
>
<!ATTLIST  funct
    indent    CDATA    "0"
>
<!ATTLIST  code
    indent    CDATA    "0"
>

<!ATTLIST  switch
    indent    CDATA    "0"
>
<!ATTLIST  foreach
    indent    CDATA    "0"
>
<!ATTLIST  if
    indent    CDATA    "0"
>
<!ATTLIST  cbody
    indent    CDATA    "0"
>

<!ATTLIST  include
    indent    CDATA    "0"
>

<!-- comment -->
<!ATTLIST comment
    type    (code|doc) "code"
 >
 
<!-- slist -->
<!ATTLIST slist
    type    (global|local) "global"
 >
 
<!-- tag -->
<!ATTLIST tag
    type    (root|local) "local"
 >
 
 <!-- inheritance type -->
<!ATTLIST inheritance
    type    (root|mrb) #REQUIRED
 >
 
<!-- r (root) and m (marabou) class refs -->
<!ATTLIST r
    class CDATA #IMPLIED
 >
<!ATTLIST m
    class CDATA #IMPLIED
 >
<!-- r (root) and m (marabou) method refs -->
<!ATTLIST rm
    class CDATA #REQUIRED
 >
<!ATTLIST mm
    class CDATA #REQUIRED
 >

=== svn2github/marabou/templates/config-xml/Analyze_DummyMethods.cxx.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE mrbcode SYSTEM "mrbcode.dtd">

<?xml-stylesheet type="text/xsl" href="mrbcode.xsl" ?>

<mrbcode type="selective">
    <method indent="1">
    <tag>DUMMY_INITIALIZE_CODE</tag>
    <methodHdr>
        <mname>InitializeUserCode</mname>
        <cname><m>TMrbAnalyze</m></cname>
        <purp>Initialize user code</purp>
        <argList>
            <arg>
                <aname>IOSpec</aname>
                <atype><m>TMrbIOSpec</m> *</atype>
                <descr>i/o specifications</descr>
            </arg>
            <arg>
                <aname>BeforeHB</aname>
                <atype>Bool_t</atype>
                <descr>kTRUE if called before booking histos</descr>
            </arg>
        </argList>
        <returnVal>
            <arg>
                <aname>Flag</aname>
                <atype>Bool_t</atype>
                <descr>kTRUE/kFALSE</descr>
            </arg>
        </returnVal>
        <descr>Dummy method, may be overwritten by user's own code<nl/>Will be called twice: <b>before</b> and <b>after</b> booking histograms</descr>
    </methodHdr>
    <code indent="2">
        <cbody>
            <l>return(kFALSE);</l>
        </cbody>
    </code>			
</method>
<method indent="1">
    <tag>DUMMY_HANDLE_MESSAGES</tag>
    <methodHdr>
        <mname>HandleMessage</mname>
        <cname><m>TMrbAnalyze</m></cname>
        <purp>Respond to message requests sent by the message handler</purp>
        <argList>
            <arg>
                <aname>Args</aname>
                <atype>Char_t *</atype>
                <descr>argument list</descr>
            </arg>
        </argList>
        <returnVal>
            <arg>
                <aname>Flag</aname>
                <atype>Bool_t</atype>
                <descr>kTRUE/kFALSE</descr>
            </arg>
        </returnVal>
        <descr>Dummy method, may be overwritten by user's own code</descr>
    </methodHdr>
    <code indent="2"><cbody>
        <l>return(kFALSE);</l>
    </cbody></code>			
</method>
<method indent="1">
    <tag>DUMMY_RELOAD_PARAMS</tag>
    <methodHdr>
        <mname>ReloadParams</mname>
        <cname><m>TMrbAnalyze</m></cname>
        <purp>Reload parameters from file</purp>
        <argList>
            <arg>
                <aname>IOSpec</aname>
                <atype><m>TMrbIOSpec</m> *</atype>
                <descr>i/o specifications</descr>
            </arg>
        </argList>
        <returnVal>
            <arg>
                <aname>Flag</aname>
                <atype>Bool_t</atype>
                <descr>kTRUE/kFALSE</descr>
            </arg>
        </returnVal>
        <descr>Dummy method, may be overwritten by user's own code</descr>
    </methodHdr>
    <code indent="2">
        <cbody>
            <l>Bool_t sts = <m class="TMrbAnalyze">this</m>-><mm class="TMrbAnalyze">ReloadVarsAndWdws</mm>(<m class="TMrbIOSpec">IOSpec</m>);	// read specs from file (ascii or ROOT)</l>
            <l><m class="TMrbAnalyze">this</m>->AdjustWindowPointers();	// fix address for 2-dim windows</l>
            <l>return(sts);	</l>
        </cbody>
    </code>			
</method>
<method indent="1">
    <tag>DUMMY_FINISH_RUN</tag>
    <methodHdr>
        <mname>FinishRun</mname>
        <cname><m>TMrbAnalyze</m></cname>
        <purp>Do some work at end of run</purp>
        <argList>
            <arg>
                <aname>BeforeSH</aname>
                <atype>Bool_t</atype>
                <descr>kTRUE if called before saving histos</descr>
            </arg>
        </argList>
        <returnVal>
            <arg>
                <aname>Flag</aname>
                <atype>Bool_t</atype>
                <descr>kTRUE/kFALSE</descr>
            </arg>
        </returnVal>
        <descr>Dummy method, may be overwritten by user's own code<nl/>Will be called twice: <b>before</b> and <b>after</b> saving histograms</descr>
    </methodHdr>
    <code indent="2">
        <cbody>
            <l>return(kFALSE);</l>
        </cbody>
    </code>			
</method>
</mrbcode>

=== svn2github/marabou/templates/config-xml/Analyze_WriteRootTree.cxx.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE mrbcode SYSTEM "mrbcode.dtd">

<?xml-stylesheet type="text/xsl" href="mrbcode.xsl" ?>

<mrbcode type="contiguous">
    <method indent="1">
    <methodHdr>
        <mname>WriteRootTree</mname>
        <cname><m>TMrbAnalyze</m></cname>
        <purp>Open a file to write raw data to tree</purp>
        <argList>
            <arg>
                <aname>IOSpec</aname>
                <atype><m>TMrbIOSpec</m> *</atype>
                <descr>i/o specifications</descr>
            </arg>
        </argList>
        <returnVal>
            <arg>
                <aname>Flag</aname>
                <atype>Bool_t</atype>
                <descr>kTRUE/kFALSE</descr>
            </arg>
        </returnVal>
    </methodHdr>
    <code>
        <cbody>
            <l><r>TString</r> rootFile;</l>
            <l>if ((<m class="TMrbIOSpec">IOSpec</m>->GetOutputMode() &amp; <m>TMrbIOSpec</m>::kOutputOpen) == 0) return(kTRUE);</l>
            
            <l>if (fWriteRootTree) {</l>
            <l>	<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Err</mm>() &lt;&lt; "ROOT file already open - " &lt;&lt; fRootFileOut-><rm class="TObject">GetName</rm>() &lt;&lt; endl;</l>
            <l>	<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Flush</mm>(<m class="TMrbAnalyze">this</m>-><rm class="TObject">ClassName</rm>(), "WriteRootTree");</l>
            <l>	return(kFALSE);</l>
            <l>}</l>
            
            <l>rootFile = IOSpec->GetOutputFile();</l>
            
            <l>if (verboseMode) {</l>
            <l>	<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Out</mm>() &lt;&lt; "Opening ROOT file \"" &lt;&lt; rootFile &lt;&lt; "\"" &lt;&lt; endl;</l>
            <l>	<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Flush</mm>(<m class="TMrbAnalyze">this</m>-><rm class="TObject">ClassName</rm>(), "WriteRootTree");</l>
            <l>}</l>
            
            <l>fRootFileOut = new <r>TFile</r>(rootFile.Data(), "RECREATE", "<s>expTitle</s>");</l>
            <l>fRootFileOut-><rm class="TFile">SetCompressionLevel</rm>(1);</l>
            <l>fWriteRootTree = kTRUE;</l>
            
            <l>// create trees for start/stop info</l>
            <l><m class="TUsrEvtStart">gStartEvent</m>-><mm class="TUsrEvtStart">CreateTree</mm>();</l>
            <l><m class="TUsrEvtStop">gStopEvent</m>-><mm class="TUsrEvtStop">CreateTree</mm>();</l>
            
            <l>// create tree to hold dead-time data</l>
            <l><m class="TUsrDeadTime">gDeadTime</m>-><mm class="TUsrDeadTime">CreateTree</mm>();</l>
        </cbody>
        <foreach indent="2">
            <tag>EVT_CREATE_TREE</tag>
            <comment type="code">create ROOT trees for each event</comment>
            <item>event</item>
            <descr>once per event</descr>
            <slist>
                <subst><sname>className</sname><descr>class name</descr></subst>
                <subst><sname>evtName</sname><descr>event name</descr></subst>
                <subst><sname>trigNo</sname><descr>trigger number</descr></subst>
                <subst><sname>eventType</sname><descr>event type: E=readout/hardware, U=user-defined</descr></subst>
            </slist>
            <switch indent="3">
                <item>eventType</item>
                <case>
                    <tag>E</tag>
                    <descr>normal (hardware) event</descr>
                    <cbody>
                        <l>g<S>className</S>->CreateTree();  // event <s>evtName</s>, trigger <s>trigNo</s></l>
                    </cbody>
                </case>
                <case>
                    <tag>U</tag>
                    <descr>user-defined event</descr>
                    <cbody>
                        <l>g<S>className</S>->CreateTree(); // user-defined event <s>className</s></l>
                    </cbody>
                </case>
            </switch>
        </foreach>
        <foreach indent="2">
            <tag>EVT_SET_WRITE_TREE</tag>
            <comment type="code">control tree output individually for each event</comment>
            <item>event</item>
            <descr>once per event</descr>
            <slist>
                <subst><sname>className</sname><descr>class name</descr></subst>
                <subst><sname>evtName</sname><descr>event name</descr></subst>
                <subst><sname>trigNo</sname><descr>trigger number</descr></subst>
                <subst><sname>eventType</sname><descr>event type: E=readout/hardware, U=user-defined</descr></subst>
            </slist>
            <switch indent="3">
                <item>eventType</item>
                <case>
                    <tag>E</tag>
                    <descr>normal (hardware) event</descr>
                    <cbody>
                        <l>// event <s>evtName</s>, trigger <s>trigNo</s></l>
                        <l>g<S>className</S>->WriteTree(<r class="TEnv">gEnv</r>-><rm class="TEnv">GetValue</rm>(<m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">GetResource</mm>("Event.<S>evtName</S>.WriteTree"), kTRUE));</l>										
                        <l>if (!g<S>className</S>->TreeToBeWritten()) {</l>
                        <l>	<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Wrn</mm>() &lt;&lt; "Output of tree data TURNED OFF for event \"<s>evtName</s>\"" &lt;&lt; endl;</l>
                        <l>	<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Flush</mm>(<m class="TMrbAnalyze">this</m>-><rm class="TObject">ClassName</rm>(), "WriteRootTree");</l>
                        <l>}</l>
                    </cbody>
                </case>
                <case>
                    <tag>U</tag>
                    <descr>user-defined event</descr>
                    <cbody>
                        <l>// user-defined event <s>className</s></l>
                        <l>g<S>className</S>->WriteTree(<r class="TEnv">gEnv</r>-><rm class="TEnv">GetValue</rm>(<m class="TMrbAnalyze">gMrbAnalyze</m>-><mm class="TMrbAnalyze">GetResource</mm>("Event.<S>evtName</S>.WriteTree"), kTRUE));</l>	
                        <l>if (!g<S>className</S>->TreeToBeWritten()) {</l>
                        <l>	<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Wrn</mm>() &lt;&lt; "Output of tree data TURNED OFF for event \"<s>className</s>\"" &lt;&lt; endl;</l>
                        <l>	<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Flush</mm>(<m class="TMrbAnalyze">this</m>-><rm class="TObject">ClassName</rm>(), "WriteRootTree");</l>
                        <l>}</l>
                    </cbody>
                </case>
            </switch>
        </foreach>
    </code>
    </method>
    </mrbcode>

=== svn2github/marabou/templates/config-xml/Analyze_ReplayTreeData.cxx.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE mrbcode SYSTEM "mrbcode.dtd">

<?xml-stylesheet type="text/xsl" href="mrbcode.xsl" ?>

<mrbcode type="contiguous">
    <method indent="1">
    <methodHdr>
        <mname>ReplayEvents</mname>
        <cname><m>TMrbAnalyze</m></cname>
        <purp>Read data from ROOT file</purp>
        <argList>
            <arg>
                <aname>IOSpec</aname>
                <atype><m>TMrbIOSpec</m> *</atype>
                <descr>i/o specifications</descr>
            </arg>
        </argList>
        <returnVal>
            <arg>
                <aname>Flag</aname>
                <atype>Bool_t</atype>
                <descr>kTRUE/kFALSE</descr>
            </arg>
        </returnVal>
        <descr>Opens an existing raw data file (replay mode only)</descr>
    </methodHdr>
    <code>			
        <cbody><l>Bool_t sts;</l>
            <l>if (!<m class="TMrbAnalyze">this</m>-><mm class="TMrbAnalyze">IsFakeMode</mm>()) {</l>
            <l>	if (fRootFileIn == NULL) {</l>
            <l>		<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Err</mm>() &lt;&lt; "No ROOT file open" &lt;&lt; endl;</l>
            <l>		<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Flush</mm>(<m class="TMrbAnalyze">this</m>-><rm class="TObject">ClassName</rm>(), "ReplayEvents");</l>
            <l>		return(kFALSE);</l>
            <l>	}</l>
            <nl/>
            <l>// output start/stop time stamps</l>
            <l>	this->PrintStartStop();</l>
            <l>}</l>
            <nl/>
            <l>sts = kTRUE;</l>
        </cbody>
        <foreach indent="2">
            <tag>EVT_REPLAY_TREE</tag>
            <comment type="code">replay tree data for each event with replay mode turned-on</comment>
            <item>event</item>
            <descr>once per event</descr>
            <slist>
                <subst><sname>className</sname><descr>class name</descr></subst>
                <subst><sname>evtName</sname><descr>event name</descr></subst>
                <subst><sname>trigNo</sname><descr>trigger number</descr></subst>
                <subst><sname>eventType</sname><descr>event type: E=readout/hardware, U=user-defined</descr></subst>
            </slist>
            <switch indent="3">
                <item>eventType</item>
                <case>
                    <tag>E</tag>
                    <descr>normal (hardware) event</descr>
                    <cbody>
                        <l>// event <s>evtName</s>, trigger <s>trigNo</s></l>
                        <l>if (g<S>evtName</S>->IsReplayMode()) {</l>									
                        <l>	if (!g<S>evtName</S>->ReplayTreeData(<m class="TMrbIOSpec">IOSpec</m>)) sts = kFALSE;</l>
                        <l>}</l>
                    </cbody>
                </case>
                <case>
                    <tag>U</tag>
                    <descr>user-defined event</descr>
                    <cbody>
                        <l>// user-defined event <s>className</s></l>
                        <l>if (g<S>className</S>->IsReplayMode()) {</l>
                        <l>	if (!g<S>className</S>->ReplayTreeData(<m class="TMrbIOSpec">IOSpec</m>)) sts = kFALSE;</l>
                        <l>}</l>
                    </cbody>
                </case>
            </switch>
        </foreach>
        <cbody><l>return(sts);</l></cbody>
    </code>
</method>
</mrbcode>

=== svn2github/marabou/templates/config-xml/Analyze_OpenRootFile.cxx.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE mrbcode SYSTEM "mrbcode.dtd">

<?xml-stylesheet type="text/xsl" href="mrbcode.xsl" ?>

<mrbcode type="contiguous">
    <method indent="1">
    <methodHdr>
        <mname>OpenRootFile</mname>
        <cname><m>TMrbAnalyze</m></cname>
        <purp>Open a file to replay tree data</purp>
        <argList>
            <arg>
                <aname>IOSpec</aname>
                <atype><m>TMrbIOSpec</m> *</atype>
                <descr>i/o specifications</descr>
            </arg>
        </argList>
        <returnVal>
            <arg>
                <aname>Flag</aname>
                <atype>Bool_t</atype>
                <descr>kTRUE/kFALSE</descr>
            </arg>
        </returnVal>
        <descr>Opens an existing raw data file (replay mode only)</descr>
    </methodHdr>
    <code>
        <cbody>
            <l><r>TString</r> rootFile;</l>
            <l>if ((<m class="TMrbIOSpec">IOSpec</m>->GetInputMode() &amp; <m>TMrbIOSpec</m>::kInputRoot) == 0) return(kTRUE);</l>
            
            <l>if (fRootFileIn != NULL) {</l>
            <l>	<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Err</mm>() &lt;&lt; "ROOT file already open - " &lt;&lt; fRootFileOut-><rm class="TObject">GetName</rm>() &lt;&lt; endl;</l>
            <l>	<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Flush</mm>(<m class="TMrbAnalyze">this</m>-><rm class="TObject">ClassName</rm>(), "OpenRootFile");</l>
            <l>	return(kFALSE);</l>
            <l>}</l>
            <l>rootFile = IOSpec->GetInputFile();</l>
            <l>if (rootFile.<rm class="TString">CompareTo</rm>("fake.root") == 0) {</l>
            <l>	<m class="TMrbAnalyze">this</m>->SetFakeMode();</l>
        </cbody>
        <foreach indent="2">
            <tag>EVT_SET_FAKE_MODE</tag>
            <comment type="code">set fake mode for all trees</comment>
            <item>event</item>
            <descr>once per event</descr>
            <slist>
                <subst><sname>className</sname><descr>class name</descr></subst>
                <subst><sname>evtName</sname><descr>event name</descr></subst>
                <subst><sname>trigNo</sname><descr>trigger number</descr></subst>
                <subst><sname>eventType</sname><descr>event type: E=readout/hardware, U=user-defined</descr></subst>
            </slist>
            <switch indent="3">
                <item>eventType</item>
                <case>
                    <tag>E</tag>
                    <descr>normal (hardware) event</descr>
                    <cbody>
                        <l>// event <s>evtName</s>, trigger <s>trigNo</s></l>
                        <l>	g<S>className</S>->SetFakeMode();</l>										
                    </cbody>
                </case>
                <case>
                    <tag>U</tag>
                    <descr>user-defined event</descr>
                    <cbody>
                        <l>// user-defined event <s>className</s></l>
                        <l>g<S>className</S>->SetFakeMode();</l>
                    </cbody>
                </case>
            </switch>
        </foreach>
        <cbody>
            <l>	if (verboseMode) {</l>
            <l>		<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Err</mm>() &lt;&lt; "Running in FAKE mode" &lt;&lt; endl;</l>
            <l>		<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Flush</mm>(<m class="TMrbAnalyze">this</m>-><rm class="TObject">ClassName</rm>(), "OpenRootFile");</l>
            <l>		return(kFALSE);</l>
            <l>	}</l>
            <l>} else {</l>
            <l>	<m class="TSystem">gSystem</m>-><mm class="TSystem">ExpandPathName</mm>(rootFile);</l>
            <l>	if(<m class="TSystem">gSystem</m>-><mm class="TSystem">AccessPathName</mm>(rootFile, kFileExists)){</l>
            <l>		<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Err</mm>() &lt;&lt; "No such file - " &lt;&lt;  rootFile &lt;&lt; endl;</l>
            <l>		<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Flush</mm>(<m class="TMrbAnalyze">this</m>-><rm class="TObject">ClassName</rm>(), "OpenRootFile");</l>
            <l>		return(kFALSE);</l>
            <l>	} else if (verboseMode) {</l>
            <l>		<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Out</mm>() &lt;&lt; "Opening ROOT file \"" &lt;&lt; rootFile &lt;&lt; "\"" &lt;&lt; endl;</l>
            <l>		<m class="TMrbLogger">gMrbLog</m>-><mm class="TMrbLogger">Flush</mm>(<m class="TMrbAnalyze">this</m>-><rm class="TObject">ClassName</rm>(), "WriteRootTree");</l>
            <l>	}</l>
            <l>}</l>
        </cbody>
    </code>
</method>
</mrbcode>
